[tools]
atmos = '1.201.0'
helm = '3.19.2'
k3s = '1.30.0+k3s1'
k9s = '0.50.9'
kubeconform = '0.6.7'
oci = '3.70.1'
packer = '1.14.3'
pre-commit = '4.5.0'
python = '3.14.0'
terraform = '1.14.0'
tflint = '0.58.1'
trivy = '0.65.0'
