[tools]
atmos = '1.202.1'
helm = '3.19.4'
k3s = '1.30.0+k3s1'
k9s = '0.50.9'
kubeconform = '0.6.7'
oci = '3.71.4'
packer = '1.14.3'
pre-commit = '4.5.1'
python = '3.14.2'
terraform = '1.14.3'
tflint = '0.58.1'
trivy = '0.65.0'
